# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/singen_clock.xdc

# XDC: imports/sysgen/singen.xdc

# Block Designs: bd/singen_bd/singen_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singen_bd || ORIG_REF_NAME==singen_bd} -quiet] -quiet

# IP: bd/singen_bd/ip/singen_bd_singen_1_0/singen_bd_singen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singen_bd_singen_1_0 || ORIG_REF_NAME==singen_bd_singen_1_0} -quiet] -quiet

# XDC: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/singen_bd_ooc.xdc
