# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/pidsg_clock.xdc

# XDC: imports/sysgen/pidsg.xdc

# Block Designs: bd/pidsg_bd/pidsg_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidsg_bd || ORIG_REF_NAME==pidsg_bd} -quiet] -quiet

# IP: bd/pidsg_bd/ip/pidsg_bd_pidsg_1_0/pidsg_bd_pidsg_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidsg_bd_pidsg_1_0 || ORIG_REF_NAME==pidsg_bd_pidsg_1_0} -quiet] -quiet

# XDC: c:/home/valerix/MaxIV/year2021/xilinxworks/pid_panda/netlist/ip_catalog/pidsg.gen/sources_1/bd/pidsg_bd/pidsg_bd_ooc.xdc
