# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.srcs/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/singen_bd_singen_1_0.xci
# IP: The module: 'singen_bd_singen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/singen_dds_compiler_v6_0_i0/singen_dds_compiler_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singen_dds_compiler_v6_0_i0 || ORIG_REF_NAME==singen_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/singen_mult_gen_v12_0_i0/singen_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singen_mult_gen_v12_0_i0 || ORIG_REF_NAME==singen_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/constrs/singen.xdc
# XDC: The top module name and the constraint reference have the same name: 'singen_bd_singen_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.srcs/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/singen_bd_singen_1_0.xci
# IP: The module: 'singen_bd_singen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/singen_dds_compiler_v6_0_i0/singen_dds_compiler_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singen_dds_compiler_v6_0_i0 || ORIG_REF_NAME==singen_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/singen_mult_gen_v12_0_i0/singen_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singen_mult_gen_v12_0_i0 || ORIG_REF_NAME==singen_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/home/valerix/MaxIV/year2021/xilinxworks/singen/netlist/ip_catalog/singen.gen/sources_1/bd/singen_bd/ip/singen_bd_singen_1_0/constrs/singen.xdc
# XDC: The top module name and the constraint reference have the same name: 'singen_bd_singen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
